### ISSUE TITLE
 Tutorial project template in docs is not working 

### ISSUE THREAD

**Issue by arthurGrigo** [research-virtualfortknox/msb-client-websocket-python#15]
**Describe the bug**

https://github.com/research-virtualfortknox/msb-client-websocket-python/tree/master/doc/tutorials/create_service_and_communicate_with_msb/project_template

Tutorial project template in docs is not working. 

Should be updated. Maybe use the app_sample.py.

**To Reproduce**

Try to execute the tutorial in the docs.

**Expected behavior**
Runnable MSB-Client.

**Screenshots**
-

**Environment (please complete the following information):**
-

**Additional context**
-

**Comment by ipamaas** [comment]
Tested the tutorial in a clean environment (pipenv-based). Could not find any issues with the tutorial. The readme of tutorial has been extended for pipenv usage if you want to retest it.
