### ISSUE TITLE
Event caching is not work

### ISSUE THREAD

**Issue by rawadh** [research-virtualfortknox/msb-client-websocket-python#2]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**

we can't publish an event directly after the register function:
myMsbClient.register()
myMsbClient.publish(
    "E1",
    'Test Event',
    2)

unless we define a timeout before publishing the event like below:
myMsbClient.register()
time.sleep(10)
myMsbClient.publish(
    "E1",
    'Test Event',
    2)

**Expected behavior:**

we should be able to publish a defined event immediately after registering our client with MSB.
myMsbClient.register()
myMsbClient.publish(
    "E1",
    'Test Event',
    2
)
**Steps to reproduce:**

I defined a MSB client and set EventCache atrribute to False value as below:
myMsbClient.disableEventCache(False)
myMsbClient.connect(msb_url)
myMsbClient.register()

and after defining an event and a responding function we want to publish an event, but we notcied that publishing the event directly after the register function is not working at all and we don't get a IO_PUBLISHED response from the MSB. therefore we had  to set a time out in order to publish the event after registering the client. 
The code below shows an example:

myMsbClient.register()
time.sleep(10)   # without this instruction we don't get IO_PUBLISHED response

event_id = "E1"
event_value = 'Rawad Test Event'
event_priority = 2
myMsbClient.publish(
    "E1",
    'Rawad Test Event',
    2
)

**MSB client version:** x.y.z

**MSB server version:** x.y.z-RELEASE

**Anything else:**

**Comment by ipamaas** [comment]
Caching need to be enabled also per event.. See the isCached parameter:

```python
event_id = "E1"
event_value = 'Hello World!'
event_priority = 2
event_isCached = True

myMsbClient.publish(
  event_id, 
  event_value,
  event_priority,
  event_isCached,
)
```
So the event will be send after registration has succeeded.

Without active event caching, another option would be to wait for the ```egistered``` property to be true:
```python
            myMsbClient.register()
            # wait for IO_REGISTERED
            timeout = time.time() + 60
            while True:
                if myMsbClient.registered:
                    logging.info("IO_REGISTERED detected")
                    break
                if time.time() > timeout:
                    self.assertTrue(
                        myMsbClient.registered,
                        "Could not detect an IO_REGISTERED within an acceptable timeframe",
                    )
                    break
                time.sleep(5)
```
