### ISSUE TITLE
Search path for application.properties

### ISSUE THREAD

**Issue by theuser1** [research-virtualfortknox/msb-client-websocket-python#4]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other

**Current behavior:**
The application.properties is loaded from the current working directory:
`config = open("application.properties", "r")`

This works in most cases, but in edge cases like ROS the working directory is not set properly for the current node. 

**Expected behavior:**
The user should be able to provide a path where the application.properties are stored. Otherwise the file should be searched in the working directory.

**MSB client version:** 1.0.2

**Comment by ipamaas** [comment]
Added in v1.0.4

You can now set a custom path to the `application.properties` file in MsbClient constructor.

```python
myMsbClient = MsbClient(applicationPropertiesCustomPath="./your/path/to/application.properties")
```
